import * as Blockly from 'blockly'

export const kittenTheme = Blockly.Theme.defineTheme('kitten-style', {
  name: 'kitten-style',
  base: Blockly.Themes.Classic,
  blockStyles: {
    turtle_blocks: { colourPrimary: '#FF9A76', colourSecondary: '#FFB79A', colourTertiary: '#FFD4BC' },
    redstone_blocks: { colourPrimary: '#FF6B6B', colourSecondary: '#FF9999', colourTertiary: '#FFBBBB' },
    fs_blocks: { colourPrimary: '#FFD93D', colourSecondary: '#FFE680', colourTertiary: '#FFF0B3' },
    http_blocks: { colourPrimary: '#4ECDC4', colourSecondary: '#7EDDD6', colourTertiary: '#B0EDE8' },
    peripheral_blocks: { colourPrimary: '#9B59B6', colourSecondary: '#BB8FCE', colourTertiary: '#D5B8E3' },
    os_blocks: { colourPrimary: '#4D96FF', colourSecondary: '#7EB6FF', colourTertiary: '#B0D4FF' },
    math_blocks: { colourPrimary: '#6BCB77', colourSecondary: '#96D99A', colourTertiary: '#C0E7C3' },
    speaker_blocks: { colourPrimary: '#FF8A5C', colourSecondary: '#FFB088', colourTertiary: '#FFD4B8' },
    control_blocks: { colourPrimary: '#FFD93D', colourSecondary: '#FFE680', colourTertiary: '#FFF0B3' },
    variable_blocks: { colourPrimary: '#4D96FF', colourSecondary: '#7EB6FF', colourTertiary: '#B0D4FF' },
    logic_blocks: { colourPrimary: '#6BCB77', colourSecondary: '#96D99A', colourTertiary: '#C0E7C3' },
    text_blocks: { colourPrimary: '#5DADE2', colourSecondary: '#85C1E9', colourTertiary: '#AED6F1' },
  },
  categoryStyles: {
    turtle_category: { colour: '#FF9A76' },
    redstone_category: { colour: '#FF6B6B' },
    fs_category: { colour: '#FFD93D' },
    http_category: { colour: '#4ECDC4' },
    peripheral_category: { colour: '#9B59B6' },
    os_category: { colour: '#4D96FF' },
    math_category: { colour: '#6BCB77' },
    speaker_category: { colour: '#FF8A5C' },
    control_category: { colour: '#FFD93D' },
    variable_category: { colour: '#4D96FF' },
    logic_category: { colour: '#6BCB77' },
    text_category: { colour: '#5DADE2' },
  },
  componentStyles: {
    workspaceBackgroundColour: '#F0F2F5',
    toolboxBackgroundColour: '#FFFFFF',
    toolboxForegroundColour: '#333333',
    flyoutBackgroundColour: '#F7F8FA',
    flyoutForegroundColour: '#333333',
    flyoutOpacity: 0.95,
    scrollbarColour: '#C0C4CC',
    scrollbarOpacity: 0.6,
    insertionMarkerColour: '#4D96FF',
    insertionMarkerOpacity: 0.4,
  },
  fontStyle: {
    family: "'PingFang SC', 'Noto Sans SC', sans-serif",
    weight: '600',
    size: 12,
  },
  startHats: true,
})
